# Numpy

- NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [1]:
import numpy as np

In [2]:
#creating 1D array 

arr1 = np.array([1,2,3,4,5])   # anything set,list,tuple can be given

print(type(arr1))
print(np.shape(arr1))          # to get shape of array
print(arr1)
arr1

<class 'numpy.ndarray'>
(5,)
[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [3]:
#creating 2D array 

arr2 = np.array([[1,2,3,4,5]])    

arr2a = np.array([[1,2,3,4,5],[6,7,8,9,0]])

arr2b = np.reshape(arr1,(1,5))    #reshaping 1D array (we can reshape any array tho)


print(arr2,"\n")
print(arr2a,"\n")
print(arr2b)


[[1 2 3 4 5]] 

[[1 2 3 4 5]
 [6 7 8 9 0]] 

[[1 2 3 4 5]]


In [4]:
# note : shape of (n,) and (n,1) are different  

In [5]:
# other ways of creating array using built-in function

arr3 = np.arange(0,11,2)       #gives a 1D array 
print(arr3)


arr3a = np.arange(0,11,2).reshape(6,)
print(arr3a)

[ 0  2  4  6  8 10]
[ 0  2  4  6  8 10]


In [6]:
## Note : in numpy Axis = 0 ---> vertical axis and Axis = 1 ----> horizontal axis

arr = np.random.randint(1,21,size = (4,5))
print("Array :\n",arr)
print("Row wise sum : ", np.sum(arr,axis = 1))
print("Column wise sum :", np.sum(arr,axis = 0))

Array :
 [[ 1 11 11  8  4]
 [17 15  9  8 16]
 [11  4 19  6 12]
 [ 1  1  2  7 13]]
Row wise sum :  [35 65 52 24]
Column wise sum : [30 31 41 29 45]


In [7]:
#. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

arr = np.arange(1,10).reshape(3,3)
print("Original array :\n",arr)

normalized_array = (arr - np.mean(arr)) / np.std(arr)

print("Normalized array:\n",normalized_array)



Original array :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array:
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


#### Broadcasting 

broadcasting refers to the ability of the library to perform element-wise operations on arrays of different shapes in a way that makes the smaller array “broadcast” across the larger array to match its shape.

In [8]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
## Adding a scalar

arr1 = arr+10
arr1

array([[11, 12, 13],
       [14, 15, 16]])

In [10]:
## Broadcasting 1D array in 2D array (horizontally)
arrA = np.array([10,20,30])      

arr2 = arr + arrA
arr2

array([[11, 22, 33],
       [14, 25, 36]])

In [11]:
## Broadcasting 1D array in 2D array (Vertically)

arrA = np.array([10,20]).reshape((2,1)) # OR np.array([[10],[20]])

arr2 = arr+arrA
arr2


array([[11, 12, 13],
       [24, 25, 26]])

In [12]:
import numpy as np  # Ensure NumPy is imported

# Creating a 3x3 matrix
arr = np.arange(1, 10).reshape(3, 3)

print("Original matrix :\n", arr, "\n")

# Determinant
det_m = np.linalg.det(arr)
print("Determinant :\n", det_m, "\n")  # Close to 0 (Singular matrix)

# Check if the matrix is singular before computing the inverse
if np.isclose(det_m, 0):
    print("Matrix is singular, inverse does not exist.\n")
else:
    Inverse = np.linalg.inv(arr)  # Compute inverse only if determinant is non-zero
    print("Inverse matrix :\n", Inverse, "\n")

# Creating two matrices for multiplication
arr1 = np.arange(1, 7).reshape(2, 3)
arr2 = np.arange(7, 13).reshape(3, 2)

# Matrix multiplication
result = arr1 @ arr2  # More readable than np.dot()
print("Matrix multiplication result:\n", result)


Original matrix :
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Determinant :
 0.0 

Matrix is singular, inverse does not exist.

Matrix multiplication result:
 [[ 58  64]
 [139 154]]


### Indexing & Slicing

#### 1. Fancy indexing

In [13]:
# Getting elements

elements = np.arange(1,10).reshape(3,3)
print("Original array :\n",elements,"\n")

print(elements[0,0])
print(elements[0][0])
print(elements[2,1])

Original array :
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

1
1
8


In [14]:
# 1D array
D1arr = np.array([1,2,3,4,5])

D1arr[[0,2,4]]     # This is how to access more than one elements   

array([1, 3, 5])

In [15]:
# 2D array
D2arr = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

D2arr[[0,0,-1,-1],[0,-1,0,-1]]  #this will give elements at (0,0),(0,-1),(-1,0),(-1,-1)


array([1, 3, 7, 9])

In [16]:
''' Slicing '''

arr = np.arange(1,10).reshape(3,3)
print("Original array :\n",arr,"\n")

row1 = arr[0]
print("row1:\n",row1,"\n")

column1 = arr[:,0]
print("column1:\n",column1,"\n")



Original array :
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

row1:
 [1 2 3] 

column1:
 [1 4 7] 



In [17]:
# Fancy indexing with slicing

arr = np.arange(1,17).reshape(4,4)
print("Original array :\n",arr,"\n")

arr[[0,2,3], 0:2]    

Original array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 



array([[ 1,  2],
       [ 9, 10],
       [13, 14]])

#### Boolean indexing 
this is used for filtering the arrays

In [18]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])


result = matrix[matrix>5]   # we give condition for elements, if condition matched by element, it gets printed
print(result)

[ 6  7  8  9 10 11 12]


#### Structured array

In [19]:
# Define the data type with fields
# Format: ('field_name', 'data_type')
data_type = [('field1', 'i4'), ('field2', 'f4'), ('field3', 'U10')]

# Create a structured array with the defined data type
structured_array = np.array([
    (1, 2.5, 'Alice'),
    (2, 3.6, 'Bob'),
    (3, 4.7, 'Charlie')
], dtype=data_type)

# Access the structured array
print("Structured Array:\n", structured_array,"\n")

# Access individual fields
print("Field1 (integers):", structured_array['field1'])
print("Field2 (floats):", structured_array['field2'])
print("Field3 (strings):", structured_array['field3'])


Structured Array:
 [(1, 2.5, 'Alice') (2, 3.6, 'Bob') (3, 4.7, 'Charlie')] 

Field1 (integers): [1 2 3]
Field2 (floats): [2.5 3.6 4.7]
Field3 (strings): ['Alice' 'Bob' 'Charlie']


In [20]:
# sorting data in strutured array

data_type = [('Name','U10'),('Age','i4'),('Weight','f4')]

str_arr = np.array([('Arun',18,84.5),('Kishh',19,100.5),('Harsh',15,40.3)],dtype=data_type)
print("Original array :\n",str_arr,"\n")

print(str_arr['Name'])
print(str_arr['Age'])
print(str_arr['Weight'])

sorted_strarr = np.sort(str_arr,order = 'Age')
print(sorted_strarr)

Original array :
 [('Arun', 18,  84.5) ('Kishh', 19, 100.5) ('Harsh', 15,  40.3)] 

['Arun' 'Kishh' 'Harsh']
[18 19 15]
[ 84.5 100.5  40.3]
[('Harsh', 15,  40.3) ('Arun', 18,  84.5) ('Kishh', 19, 100.5)]


In [ ]:
# To check if two arrays are similar with a very small tolerance

A = np.array([1,2,3,4,5])
B = np.array([1,2,3,4,5.00002])

np.allclose(A,B)
# (Usefule in ML)

True